### ISSUE TITLE
DGEMM example is invalid SYCL

### ISSUE THREAD

**Issue by tomdeakin** [oneapispec/spec#1]
The DGEMM example on [this page](https://spec.oneapi.com/oneAPI/architecture.html#direct-programming-example) is incorrect SYCL code. 1D buffers are declared, and then 2D access (`A[row][i]`)  is used inside the kernel. This is invalid, and this code does not compile.

**Comment by mjdomeik** [comment]
Thank you, Tom. You are correct. We will get this updated shortly, targeting Friday, Nov 22.

Max

**Comment by mjdomeik** [comment]
Thanks again. The example has been updated and the issue addressed.
